var i18n = {
	validator_invalid   	  : 'Невярно',
    validator_checked   	  : 'Моля, изберете',
    validator_empty			  : 'Моля, въведете нещо тук',
    validator_min       	  : 'Недостатъчен брой символи',
    validator_max             : 'Надвишен брой символи',
    validator_number_min      : 'Твърде ниско',
    validator_number_max      : 'Твърде високо',
    validator_url             : 'Невалиден URL',
    validator_number          : 'Не е число',
    validator_email           : 'Email адреса е невалиден',
    validator_email_repeat    : 'Email адреса не съвпада',
    validator_password_repeat : 'Паролите не съвпадат',
    validator_repeat          : 'Няма съвпадение',
    validator_complete        : 'Незавършено',
    validator_select          : 'Моля, изберете нещо',
    pleaseWait                : 'Моля, изчакайте',
    no_password               : 'Няма парола',
    weak_password             : 'Слаба',
    good_password             : 'Силна',
    strong_password           : 'Много силна',
    cookiebar_text            : 'Този сайт използва "бисквитки" за да подобри предлаганите услуги.',
    cookiebar_btn             : 'ОК',
}